fail_fast: true

repos:
  - repo: local
    hooks:
      - id: test-script
        name: test-script
        entry: bash "scripts/pre-commit.sh"
        language: system
        types: [python]
        pass_filenames: false
