repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: ruff
  # We run `mypy` as a local hook because otherwise it doesn't validate against the
  # pacakges' types and arguments. Or we'd need to install all of the dependencies again
  # within the `mypy` venv as `additional_dependecies`, which is a bit silly.
  # Inspired from: https://jaredkhan.com/blog/mypy-pre-commit
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        types: [python]
        entry: inv type-check
        pass_filenames: false
        # Ensure it is only called once per commit.
        require_serial: true
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
