name: test

on:
  schedule:
    - cron: '0 0 * * *'

env:
  GALILEO_API_URL: "http://localhost:8088"
  GALILEO_MINIO_URL: "127.0.0.1:9000"
  GALILEO_MINIO_ACCESS_KEY: "minioadmin"
  GALILEO_MINIO_SECRET_KEY: "minioadmin"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: install dependencies
        run: scripts/install.sh

      - name: run dependencies
        run: scripts/run-dependencies.sh

      - name: test
        run: python scripts/run_integrations.py
