name: "Close Stale"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been identified as stale. Please leave a comment if it's still current or it'll be closed."
          stale-pr-message: "This pull request has been identified as stale. Please leave a comment if it's still current or it'll be closed."
          days-before-issue-stale: 30
          days-before-pr-stale: 30
          days-before-issue-close: 5
          days-before-pr-close: 5
